### ISSUE TITLE
script dies with "undefined local variable or method `drawables_standard'"

### ISSUE THREAD

**Issue by mnalis** [matkoniecz/rescaling_for_android#1]
running the script dies with:

```
Traceback (most recent call last):
        5: from /home/mnalis/work/openstreetmap/rescaling_for_android/rescale.rb:64:in `<main>'
        4: from /home/mnalis/work/openstreetmap/rescaling_for_android/rescale.rb:39:in `main'
        3: from /home/mnalis/work/openstreetmap/rescaling_for_android/rescale.rb:39:in `each'
        2: from /home/mnalis/work/openstreetmap/rescaling_for_android/rescale.rb:40:in `block in main'
        1: from /home/mnalis/work/openstreetmap/rescaling_for_android/rescale.rb:45:in `generate_drawable'
./rescaling_for_android/rescale.rb:33:in `drawable_sizing': undefined local variable or method `drawables_standard' for main:Object (NameError)

```

it seems it needs to be called `drawables_for_three_colums` instead of `drawables_standard`.

**Comment by matkoniecz** [comment]
Thanks for a report!
